### ISSUE TITLE
Add a button to see the page without the fasterize cache

### ISSUE THREAD

**Issue by abarre** [fasterize/chrome-fasterize-indicator#7]
We need to add an header `Cache-Control:no-fstrz-cache` in the request.

**Comment by abarre** [comment]
The problem with this feature is to determine which requests should be modified.

**Comment by stefounet** [comment]
:+1:

**Comment by abarre** [comment]
A workaround is to set an abtest to 100% and click on "See unoptimized page".

**Comment by stefounet** [comment]
It's not the same to bypass cache and see the unoptimized page, isn't it?

**Comment by abarre** [comment]
Available in the next release.
